// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: helloworld.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreetingMessage_SayHello_FullMethodName = "/helloworld.GreetingMessage/SayHello"
)

// GreetingMessageClient is the client API for GreetingMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetingMessageClient interface {
	SayHello(ctx context.Context, in *HelloworldRequest, opts ...grpc.CallOption) (*HelloworldResponse, error)
}

type greetingMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetingMessageClient(cc grpc.ClientConnInterface) GreetingMessageClient {
	return &greetingMessageClient{cc}
}

func (c *greetingMessageClient) SayHello(ctx context.Context, in *HelloworldRequest, opts ...grpc.CallOption) (*HelloworldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloworldResponse)
	err := c.cc.Invoke(ctx, GreetingMessage_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetingMessageServer is the server API for GreetingMessage service.
// All implementations must embed UnimplementedGreetingMessageServer
// for forward compatibility.
type GreetingMessageServer interface {
	SayHello(context.Context, *HelloworldRequest) (*HelloworldResponse, error)
	mustEmbedUnimplementedGreetingMessageServer()
}

// UnimplementedGreetingMessageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreetingMessageServer struct{}

func (UnimplementedGreetingMessageServer) SayHello(context.Context, *HelloworldRequest) (*HelloworldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetingMessageServer) mustEmbedUnimplementedGreetingMessageServer() {}
func (UnimplementedGreetingMessageServer) testEmbeddedByValue()                         {}

// UnsafeGreetingMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetingMessageServer will
// result in compilation errors.
type UnsafeGreetingMessageServer interface {
	mustEmbedUnimplementedGreetingMessageServer()
}

func RegisterGreetingMessageServer(s grpc.ServiceRegistrar, srv GreetingMessageServer) {
	// If the following call pancis, it indicates UnimplementedGreetingMessageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreetingMessage_ServiceDesc, srv)
}

func _GreetingMessage_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingMessageServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetingMessage_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingMessageServer).SayHello(ctx, req.(*HelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetingMessage_ServiceDesc is the grpc.ServiceDesc for GreetingMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetingMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.GreetingMessage",
	HandlerType: (*GreetingMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetingMessage_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
